### ISSUE TITLE
Support signing in with MacBook Touch ID―Chrome Desktop

### ISSUE THREAD

**Issue by grzuy** [cedarcode/webauthn-rails-demo-app#32]
[Chrome Platform Status ― Support for Touch ID as a platform authenticator via the Web Authentication API](https://www.chromestatus.com/feature/5962264427364352)

Support WebAuthn ceremonies with:

* Authenticator: MacBook Touch ID
* User agent: Chrome Desktop

**Comment by grzuy** [comment]
Conversation about this actually started here https://github.com/cedarcode/webauthn-ruby/issues/68

**Comment by sorah** [comment]
Wrongly left a note about Chrome's implementation on android issue: https://github.com/cedarcode/webauthn-rails-demo-app/issues/31#issuecomment-427280056

**Comment by grzuy** [comment]
Thank you.
I am moving your comments to this issue via quoting.

Quoting @sorah below:

> Kindly note: as of this writing,

> - Chrome 70 (beta) requires `platform` authenticatorSelection https://www.w3.org/TR/2018/CR-webauthn-20180807/#dom-publickeycredentialcreationoptions-authenticatorselection
>   - Chrome is avoiding showing system Touch ID dialog always to a user, they may need to use external authenticator and showing the system dialog may make a confuse. They're developing the dialog to ask preferred authenticator to user: https://crrev.com/c/1172912 https://crbug.com/873710 
> - On Canary, we need  `--enable-features=WebAuthenticationUI` to enable dialog which enables Touch ID without `platform` authenticatorSelection.  https://crbug.com/847985
>   - I'm looking forward to the UI rolls out...

**Comment by grzuy** [comment]
Quoting @sorah below:

> oops, this is only for registration. If we call `navigator.credentials.get()` with Touch ID's credential ID, Chrome prompts for Touch ID.

> I implemented "force platform authenticator (may enable Touch ID)" link on my app.... https://github.com/sorah/clarion/commit/1c76ba15a26606d2a4c35fc230500a300617db69

**Comment by brauliomartinezlm** [comment]
Just tested this out. Our current implementation is working fine with MacOS TouchID. I'm closing this issue.
