### ISSUE TITLE
Split registration and authentication user flows

### ISSUE THREAD

**Issue by grzuy** [cedarcode/webauthn-rails-demo-app#53]
> In hindsight it's quite logical 🤦‍♂️ SessionController does dual duty as both registration and authentication controller, depending on the availability of credentials. I'll open a PR to refactor this a bit since I find it not very intuitive or a good example for somebody's production app.

_Originally posted by @bdewater in https://github.com/cedarcode/webauthn-rails-demo-app/pull/33#issuecomment-427591687_

**Comment by grzuy** [comment]
I agree with @bdewater that having Registration with Authentication mixed in the same user flow is confusing from a end-user perspective.

**Comment by grzuy** [comment]
@bdewater Are you already in progress with this? If not I can work on it.
I do want to fix this UX confusion sooner than later :-)

Thanks!

**Comment by sandergroen** [comment]
@grzuy I already did some refactoring locally. I have separated the registration and authentication flows. I can make a pull request if you like.

**Comment by grzuy** [comment]
@sandergroen Yes, please, pull request would be great, thank you! :-)

**Comment by bdewater** [comment]
Sorry I missed the ping, did not have the time to tackle it myself but happy to see somebody else taking a stab at it :)

**Comment by grzuy** [comment]
@bdewater No worries. Thank you for raising the concern initially!

**Comment by grzuy** [comment]
Closed by #56
