### ISSUE TITLE
atob fails on user ids with underscores

### ISSUE THREAD

**Issue by ghost** [cedarcode/webauthn-rails-demo-app#66]
The Encoder [uses atob](https://github.com/cedarcode/webauthn-rails-demo-app/blob/master/app/javascript/encoder.js#L9) to [encode a user id](https://github.com/cedarcode/webauthn-rails-demo-app/blob/master/app/javascript/credential.js#L39) into a ByteArray. This fails on usernames with underscores like `cool_dude_123` (which could be a unique username used by an application).

`Uint8Array.from` should work here for encoding strings with underscores.
```
user: {
    id: Uint8Array.from(
        "UZSL85T9AFC", c => c.charCodeAt(0)),
    name: "lee@webauthn.guide",
    displayName: "Lee",
 }
```

This was taken from Duo Security's [great writeup on Webauthn](https://webauthn.guide/#registration).

**Comment by grzuy** [comment]
Hi @tomek-bt,

Thanks for the issue report!
Sorry I am not sure I totally understand what the issue is...

Are you saying that if you try register with username `cool_dude_123`, the registration doesn't work?
If that's what you saying I am not able to reproduce that, can you?

**Comment by tomek-bt** [comment]
ahh maybe I went about this the wrong way. I dropped into a Javascript console and pasted the function
```
  function strToBin(str) {
    console.log(str);
    return Uint8Array.from(atob(str), c => c.charCodeAt(0));
  }
```

Then tried `strToBin('foo_bar')`, but I can't seem to reproduce this in the web app

**Comment by grzuy** [comment]
Gotcha.
