### ISSUE TITLE
Add credential with no nickname locked out of account

### ISSUE THREAD

**Issue by tyvdh** [cedarcode/webauthn-rails-demo-app#71]
If you create an account and then add an additional key without a nickname and then logout and try to log back in you get an error.

![screen shot 2019-03-05 at 11 38 35 am](https://user-images.githubusercontent.com/4383610/53821173-3a956380-3f3b-11e9-95ab-fa97f9368a66.png)

**Comment by grzuy** [comment]
Hi @tyvdh,

Thanks for report.

I am having trouble reproduce the issue.
You say you were able to add a new credential without a nickname once signed in?

**Comment by tyvdh** [comment]
Here's a quick screencast of the issue.

http://tyler.link/982b4751048c/broken.mov

**Comment by grzuy** [comment]
> Here's a quick screencast of the issue.
> 
> http://tyler.link/982b4751048c/broken.mov

Broken link :-(

**Comment by grzuy** [comment]
Hi @tyvdh,

We've been doing some improvements lately that could have affected/fixed this issue you were having.
Given that I am closing, but please let us know if you still can reproduce the issue with the current `master` so that we re-open.

Thanks again!
