### ISSUE TITLE
Unspecified expected origin

### ISSUE THREAD

**Issue by Faisal-nfl** [cedarcode/webauthn-rails-demo-app#85]
I tried to run it locally with ngrok but on signup it crashes with error "Unspecified expected origin"
on line# 42 of RegistrationsController

`render json: { status: "forbidden" },status: :forbidden unless auth_response.verify(str_to_bin(user.current_challenge))`

**Comment by grzuy** [comment]
Hi,

You need to `$ cp .env.example .env`.

**Comment by grzuy** [comment]
That setup step was missing in the `README`, just added (https://github.com/cedarcode/webauthn-rails-demo-app/commit/d59b9969e5e58a32661810fcc83b535a33bb0e14).

**Comment by Faisal-nfl** [comment]
thanks

**Comment by grzuy** [comment]
Thanks for reporting!
